name: Build WeChatNoAds74

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: qusic/theos:latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Package
      run: |
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: WeChatNoAds74
        path: packages/*.deb
